### ISSUE TITLE
Good job!!!

### ISSUE THREAD

**Issue by okikiola11** [Albertino2020/tic-tac-toe-project#7]
Hello @Albertino2020 ,

Your project looks good, nicely implemented, properly written logic. But we noticed some issues that can be fixed as stated:
i) the use of global variables
ii) the use of count > 9, we think it can be implemented differently.

Wishing you all the best in your next project.

**Comment by Albertino2020** [comment]
Hello @okikiola11 ,

Thank you for the review.

I removed all global variables and replaced them with instance and class variables.
I also updated the while loop condition so that the counter < 9 is no longer an issue.

All the best,
Albertino

**Comment by okikiola11** [comment]
Thanks for the feedback. Wishing you all the best as you move forward in
your project.

Regards,
Okikiola.
